### ISSUE TITLE
Old Routes not being removed when updating ingress

### ISSUE THREAD

**Issue by jonstacks** [ngrok/kubernetes-ingress-controller#123]
### What happened

When updating a path in the ingress, both the old path and the new path exist as `HTTPSEdgeRoute`s. 

Ex:

```yaml
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: test
  namespace: default
  annotations:
    k8s.ngrok.com/https-compression: "true"
spec:
  ingressClassName: ngrok
  rules:
  - host: my-test.ngrok.io
    http:
      paths:
      - path: /path1   # update this to /path2
        pathType: Prefix
        backend:
          service:
            name: webhook-test
            port:
              number: 80
```

### What you think should happen instead

I expected the old route to be removed from the HTTPS Edge in ngrok and only the new route `/path2` to exist. 

### How to reproduce

Simply update the path selector on an ingress to reproduce.
