### ISSUE TITLE
Default Backends

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/kubernetes-ingress-controller#145]
### Description

K8s ingress has the concept of a default backend which isn't tied to any particular rule/route/host https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
spec:
  defaultBackend:
    service: # Service and Resource are mutually exclusive
      name: test
      port:
        number: 80
    resource: # Service and Resource are mutually exclusive
      apiGroup: k8s.example.com
      kind: StorageBucket
      name: static-assets
```

We can support services today.
For resources, when we end up creating CRDs for things like a static response backend, that would be a commonly used case for 404 responses for example.

Default backends are a bit unique though in that they don't have any host to match on. With something like nginx which is routeable via an IP, it can still create a default backend. For ngrok, if there are no hosts setup, then there will be no edge actually created. A default backend ends up only being useable when there are other ingress rules configured that result in a routeable edge. 

### Use Case

404's and other fallback pages are common usecases for the default backend
