### ISSUE TITLE
CRD Backend Support

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/kubernetes-ingress-controller#146]
### Description

Currently, we create tunnel group backends for highly available tunnels to services within a k8s cluster. Ngrok also supports these other backends:
- http response backend: static http response value
- Failover backend: takes a list of other backends
- weighted backends: takes a list of other backends

If we treat our tunnel groups as a Backend, and create crd's for these other backends that can reference each other and tunnel groups, we could use them with the ingress spec

### Use Case

```yaml
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: HttpResponseBackend
metadata:
  name: http-response-backend-404
spec:
  body: "404 Not Found"
  status: 404
---
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: FailoverBackend
metadata:
  name: failover-backend
spec:
  backends:
    - resource:
        apiGroup: ingress.k8s.ngrok.com/v1alpha1
        kind: HttpResponseBackend
        name: http-response-backend-404
    - service:
        name: test-service
        port:
          number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
spec:
  defaultBackend:
    resource:
      apiGroup: ingress.k8s.ngrok.com/v1alpha1
      kind: HttpResponseBackend
      name: http-response-backend-404
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              service: # Makes a tunnel group backend for this service
                name: test-service
                port:
                  number: 80
              resource: # References other backend types
                apiGroup: ingress.k8s.ngrok.com/v1alpha1
                kind: FailoverBackend
                name: failover-backend

```
