### ISSUE TITLE
Migrate ingress annotations to CRD

### ISSUE THREAD

**Issue by jonstacks** [ngrok/kubernetes-ingress-controller#169]
### Description

Currently, annotations on ingress objects are used to configure HTTPS Edge Modules. Example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    k8s.ngrok.com/tls-min-version: "1.3"
```

Some of the HTTPS Edge Modules are more complex and difficult to define in annotations. Additionally, there is currently no way to re-use HTTPS Edge Module configurations across ingresses.

With a CRD approach, users can define configuration for different route modules in a `NgrokModuleSet` CRD like so:

```
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: NgrokModuleSet
metadata:
  name: my-module
modules:  
  compression:
    enabled: true
  tlsTermination:
    minVersion: "1.3"
```

and re-use this configuration across multiple ingresses, like so:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-1
  annotations:
    k8s.ngrok.com/modules: "my-module"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-2
  annotations:
    k8s.ngrok.com/modules: "my-module"
```    

### Use Case

This makes it easier to share common Edge Module configuration across ingresses.
