### ISSUE TITLE
Unable to use existing secret

### ISSUE THREAD

**Issue by samip5** [ngrok/kubernetes-ingress-controller#277]
### Kubernetes Version

v1.26.3+k3s1

### Helm Chart Version

0.10.0

### Helm Chart configuration

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ngrok
  namespace: networking
spec:
  install:
    crds: CreateReplace
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress-controller
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: ngrok
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      apiKey:
        valueFrom:
          secretKeyRef:
            name: ngrok-secrets
            key: apiKey
      authtoken:
        valueFrom:
          secretKeyRef:
            name: ngrok-secrets
            key: authtoken
```

### What happened

Usually one can use valueFrom to get a key from already existing secret, but it seems that's not supported in the helm chart. Instead it throws an error:

```
NAME                    REVISION        SUSPENDED       READY   MESSAGE
ngrok                                   False           False   Helm install failed: template: kubernetes-ingress-controller/templates/credentials-secret.yaml:9:83: executing "kubernetes-ingress-controller/templates/credentials-secret.yaml" at <b64enc>: wrong type for value; expected string; got map[string]interface {}
```

### What you think should happen instead

I think it should be a supported configuration to get it from an existing secret, or have an way to tell it properly the existing secret name for the values and not rely on generating it from values.

### How to reproduce

Current helm-release can be seen here: https://github.com/samip5/k8s-cluster/blob/f6ebf02927b7d9b7773f05b55226202e95704475/cluster/apps/networking/ngrok/app/helm-release.yaml
There's also the sops secret that's encrypted and decryption is handled by Flux & sops.

**Comment by jonstacks** [comment]
@samip5, thanks for reporting the issue. We don't currently support the `valuesFrom` format you are mentioning for the API Key and Auth Token to pull them from arbitrary keys(would be a good enhancement). The helm chart does support taking them both from a single, existing secret though.

You can create a secret like the following:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: your-secret-name
  namespace: <same-namespace-as-ngrok-ingress-controller>
data:
  API_KEY: "YOUR-API-KEY-BASE64"
  AUTHTOKEN: "YOUR-AUTHTOKEN-BASE64"
```

And then reference the existing secret in the `values.yaml` like so:

```yaml
credentials:
  secret:
    name: "your-secret-name"
```
