### ISSUE TITLE
HTTP 429: Your account is rate limited to 120 API requests per minute.

### ISSUE THREAD

**Issue by 0GiS0** [ngrok/kubernetes-ingress-controller#278]
### What happened

I followed this tutorial: https://ngrok.com/docs/using-ngrok-with/k8s/ with my free account but I cannot get things done. It always said HTTP 429: Your account is rate limited to 120 API requests per minute.

I also get this other error: 

{"level":"error","ts":"2023-07-05T19:15:32Z","logger":"controllers.https-edge","msg":"unable to fetch Edge","V1Alpha1HTTPSEdge":"ngrok-ingress-controller/MY_RANDOM_VALUE-ngrok-free-app","error":"HTTPSEdge.ingress.k8s.ngrok.com \"MY_RANDOM_VALUE-ngrok-free-app\" not found","stacktrace":"github.com/ngrok/kubernetes-ingress-controller/internal/controllers.(*HTTPSEdgeReconciler).Reconcile\n\tgithub.com/ngrok/kubernetes-ingress-controller/internal/controllers/httpsedge_controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

### What you think should happen instead

I should get my ingress resource configured in ngrok egress section as the article mentioned

### How to reproduce

Following the steps using a free account

**Comment by samcrichard** [comment]
Thank you for this! I'd like to change your rate limits so you can use this while I ponder next steps. Any chance you know your account name?

**Comment by samcrichard** [comment]
Nevermind, found you and changed it.

**Comment by badal773** [comment]
Same goes for me, I am also facing same issue

**Comment by 0GiS0** [comment]
> Hello @0GiS0 , thanks for giving the ingress controller a try!
> 
> I see in the error message you posted, it says
> 
> `HTTPSEdge.ingress.k8s.ngrok.com "MY_RANDOM_VALUE-ngrok-free-app" not found`
> 
> This looks like perhaps you had some scripts to generate a random value for a hostname that didn't get substituted out. Can you check what your ingress definition and domains state
> 
> * `kubectl get ing` to see the hosts field
> * `kubectl get domains` to see what ngrok domains there are
> 
> It seems like since this domain doesn't pass the domain specification due to its underscores, the controller is looping forever trying to create it but failing. If this is the case, we can delete that ingress object _AND_ delete the domain (via `kubectl delete domain <name>`) and retry with a valid subdomain. If thats the case, we can also follow up to surface this error message in a better way and to prevent these loops.

Hi @alex-bezek!!

I put that MY_RANDOM_VALUE in this thread because I wasn't sure if It's a good idea share it publicly.

Thanks to @samcrichard now I don't have the rate limit anymore, but It's still not working. I get this error:

`{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"CircuitBreaker matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"Compression matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"IP Restriction matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"Request Headers matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"Response Headers matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"OAuth matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"OIDC matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"SAML matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"Webhook Verification matches desired state, skipping update"}
{"level":"info","ts":"2023-07-07T07:03:43Z","logger":"controllers.https-edge","msg":"Updating route","edgeID":"edghts_2SAN1ud5ack7Z5uEJJr87ZccIL6","match":"/","matchType":"path_prefix","backendID":"bkdtg_2SEYtfDAPukSPy8zCH23qWTENB0"}
{"level":"error","ts":"2023-07-07T07:03:44Z","logger":"controllers.https-edge","msg":"unable to fetch Edge","V1Alpha1HTTPSEdge":"ngrok-ingress-controller/game-e486b5a4ebf7-10727081956197939067-ngrok-free-app","error":"HTTPSEdge.ingress.k8s.ngrok.com \"game-e486b5a4ebf7-10727081956197939067-ngrok-free-app\" not found","stacktrace":"github.com/ngrok/kubernetes-ingress-controller/internal/controllers.(*HTTPSEdgeReconciler).Reconcile\n\tgithub.com/ngrok/kubernetes-ingress-controller/internal/controllers/httpsedge_controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}`

And this is my ingress resource:

```
# ngrok Ingress Controller Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048-ingress
  namespace: ngrok-ingress-controller
spec:
  ingressClassName: ngrok
  rules:
    - host: e486b5a4ebf7-10727081956197939067.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80
```

I am not sure if I can use a subdomain so I tested both:

```
# ngrok Ingress Controller Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048-ingress
  namespace: ngrok-ingress-controller
spec:
  ingressClassName: ngrok
  rules:
    - host: game.e486b5a4ebf7-10727081956197939067.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80
```

But It says the same. And I recheck my domain and it's correct:

<img width="1256" alt="image" src="https://github.com/ngrok/kubernetes-ingress-controller/assets/175379/15790097-83ea-447a-8002-19c421a62200">

Any ideas? Thank you so much!!!
