### ISSUE TITLE
Remove old helm 0.4.0 version of the ingress controller

### ISSUE THREAD

**Issue by russorat** [ngrok/kubernetes-ingress-controller#310]
### What happened

Whenever you add the helm repo, for some reason, you get two versions of ngrok charts, one listed in ngrok/kubernetes-ingress-controller which is correct, and another one listed in ngrok/ngrok-ingress-controller which is old and out of date. Is it possible to remove the legacy version?

```
  ~/workspace/ui   master !1 ❯ helm repo add ngrok https://ngrok.github.io/kubernetes-ingress-controller                                                       3.0.0 ⎈ k3d-tanzu
"ngrok" has been added to your repositories
  ~/workspace/ui   master !1 ❯ helm show chart ngrok/kubernetes-ingress-controller                                                                             3.0.0 ⎈ k3d-tanzu
apiVersion: v2
appVersion: 0.9.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: A Kubernetes ingress controller built using ngrok.
home: https://ngrok.com
icon: https://ngrok.com/static/img/brand/ngrok-favicon.svg
keywords:
- ngrok
- networking
- ingress
- edge
- api gateway
name: kubernetes-ingress-controller
sources:
- https://github.com/ngrok/kubernetes-ingress-controller
version: 0.11.0

  ~/workspace/ui   master !1 ❯ helm show chart ngrok/ngrok-ingress-controller                                                                                  3.0.0 ⎈ k3d-tanzu
apiVersion: v2
appVersion: 0.2.0
description: A Kubernetes ingress controller built using ngrok.
home: https://ngrok.com
icon: https://blog.ngrok.com/_next/image?url=%2Fassets%2Fblog%2Fplaceholder.png&w=1920&q=75
keywords:
- ngrok
- networking
- ingress
- edge
- api gateway
name: ngrok-ingress-controller
sources:
- https://github.com/ngrok/ngrok-ingress-controller
version: 0.4.0
```
