### ISSUE TITLE
 CNAME Target not being set on Ingress Status

### ISSUE THREAD

**Issue by ppapp92** [ngrok/kubernetes-ingress-controller#340]
### Kubernetes Version

1.28

### Helm Chart Version

0.12.1

### Ingress Controller Version

0.10.1

### System Info

AWS EKS
ArgoCD
ExternalDNS

### Helm Chart configuration

```
kubernetes-ingress-controller:
  replicaCount: 1
  ingressClass:
    name: ngrok
    create: true
    default: false
  controllerName: "k8s.ngrok.com/ingress-controller"
  credentials:
    apiKey: <API_KEY>
    authtoken: <AUTHTOKEN>
  region: ""
```

### What happened

When an Ngrok class ingress resource is created in K8 the Address(status.loadBalancer) doesn't get updated by the Ngrok Ingress Controller. This means that ExternalDNS does not create appropriate route53 entires to fully automate the deployment of an application.

Similar to https://github.com/ngrok/kubernetes-ingress-controller/issues/161

### What you think should happen instead

Ngrok Ingress Controller should update the ingress resource with the CNAME Target so that ExternalDNS can properly configure DNS for the newly created service/app.

### How to reproduce

Create an ingress resource in K8
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  finalizers:
  - k8s.ngrok.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.40.4
  name: argo-workflows-server
  namespace: argo
spec:
  ingressClassName: ngrok
  rules:
  - host: domain.example.com
    http:
      paths:
      - backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
        path: /
        pathType: Prefix
```
View the status of the ingress and see that the loadBalancer address is empty
```
status:
  loadBalancer: {}
```

Both the Tunnel and Domain resources get created.

```
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: Domain
metadata:
  finalizers:
  - k8s.ngrok.com/finalizer
  generation: 1
  name: example
  namespace: argo
spec:
  description: Created by kubernetes-ingress-controller
  domain: domain.example.com
  metadata: '{"owned-by":"kubernetes-ingress-controller"}'
status:
  cnameTarget: x.ngrok-cname.com
  domain: domain.example.com
  id: rd_x
  uri: https://api.ngrok.com/reserved_domains/rd_x
```

```
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: Tunnel
metadata:
  finalizers:
  - k8s.ngrok.com/finalizer
  labels:
    k8s.ngrok.com/controller-name: ingress-ngrok-kubernetes-ingress-controller-manager
    k8s.ngrok.com/controller-namespace: ingress-ngrok
    k8s.ngrok.com/port: "2746"
    k8s.ngrok.com/service: argo-workflows-server
  name: argo-workflows-server-2746-v4g2m
  namespace: argo
  ownerReferences:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: argo-workflows-server
spec:
  backend:
    protocol: HTTP
  forwardsTo: argo-workflows-server.argo.svc.cluster.local:2746
  labels:
    k8s.ngrok.com/namespace: argo
    k8s.ngrok.com/port: "2746"
    k8s.ngrok.com/service: argo-workflows-server

```
