### ISSUE TITLE
Unable to delete Load Balancer Service

### ISSUE THREAD

**Issue by jonstacks** [ngrok/kubernetes-ingress-controller#401]
### Kubernetes Version

v1.28.2

### Helm Chart Version

0.14.0

### Ingress Controller Version

0.12.0

### System Info

x86, Talos Linux v1.5.4

### Kubernetes Logs

```
{"level":"info","ts":"2024-07-16T17:44:47Z","logger":"controllers.service","msg":"Service still owns ngrok resources, waiting for deletion...","service":{"name":"ngrok-ascii-2","namespace":"default"}}
{"level":"Level(-5)","ts":"2024-07-16T17:44:47Z","msg":"Reconcile done, requeueing after 5s","controller":"service","controllerGroup":"","controllerKind":"Service","Service":{"name":"ngrok-ascii-2","namespace":"default"},"namespace":"default","name":"ngrok-ascii-2","reconcileID":"5c2303c0-749a-4109-8ef1-42638d292800"}
{"level":"debug","ts":"2024-07-16T17:44:50Z","logger":"drivers.tunnel","msg":"heartbeat received","obj":"csess","id":"ed035236b02e","clientid":"d9dd948f302f0a983b564f84fe6cc009","latency_ms":23}
{"level":"Level(-5)","ts":"2024-07-16T17:44:52Z","msg":"Reconciling","controller":"service","controllerGroup":"","controllerKind":"Service","Service":{"name":"ngrok-ascii-2","namespace":"default"},"namespace":"default","name":"ngrok-ascii-2","reconcileID":"3a84f02a-187a-45ba-90ab-510e5bae7d81"}
{"level":"info","ts":"2024-07-16T17:44:52Z","logger":"controllers.service","msg":"Service still owns ngrok resources, waiting for deletion...","service":{"name":"ngrok-ascii-2","namespace":"default"}}
{"level":"Level(-5)","ts":"2024-07-16T17:44:52Z","msg":"Reconcile done, requeueing after 5s","controller":"service","controllerGroup":"","controllerKind":"Service","Service":{"name":"ngrok-ascii-2","namespace":"default"},"namespace":"default","name":"ngrok-ascii-2","reconcileID":"3a84f02a-187a-45ba-90ab-510e5bae7d81"}
```

### What happened

When trying to delete a ngrok LoadBalancer service, it hangs and does not delete the owned resources.

### What you think should happen instead

When deleting a ngrok LoadBalancer service, it should delete the owned resources(tcpedge, tlsedge, domain, etc)

### How to reproduce

```
---
kind: Service
apiVersion: v1
metadata:
  name: delete-me-service
  namespace: default
  labels:
    app.kubernetes.io/name: delete-me
  annotations:
    k8s.ngrok.com/domain: something.ngrok.io
spec:
  type: LoadBalancer
  loadBalancerClass: ngrok
  selector:
    app.kubernetes.io/name: some-existing-service
  ports:
  - name: telnet
    port: 23
    targetPort: telnet
```

Create a service like the above that targets an existing pod selector. Then try to delete it
